name: Verify Windows install

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  SIM_DIR: examples/differential

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md**", "**LICENSE**", "docs/**"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download openEMS and gerbv
      shell: bash
      run: ./vendor/download.sh

    - name: Create python virtual environment
      shell: bash
      run: python -m venv venv

    - name: Install gerber2ems
      shell: bash
      run: |
        . ./venv/Scripts/activate
        . ./vendor/update_path.sh
        pip install -e .

    - name: Copy retry script due to openEMS randomly seg faulting
      shell: bash
      run: cp ./scripts/retry.sh /usr/bin/retry

    - name: Check if gerber2ems runs
      shell: bash
      run: |
        . ./venv/Scripts/activate
        . ./vendor/update_path.sh
        retry gerber2ems -h

    - name: Perform Gerber to image conversion
      shell: bash
      run: |
        . ./venv/Scripts/activate
        . ./vendor/update_path.sh
        cd ${{ env.SIM_DIR }}
        retry gerber2ems --debug --convert

    - name: Generate geometry files for openEMS
      shell: bash
      run: |
        . ./venv/Scripts/activate
        . ./vendor/update_path.sh
        cd ${{ env.SIM_DIR }}
        retry gerber2ems --debug --geometry

    - name: Run openEMS simulation
      shell: bash
      run: |
        . ./venv/Scripts/activate
        . ./vendor/update_path.sh
        cd ${{ env.SIM_DIR }}
        retry gerber2ems --debug --simulate

    - name: Post process the openEMS simulation data
      shell: bash
      run: |
        . ./venv/Scripts/activate
        . ./vendor/update_path.sh
        cd ${{ env.SIM_DIR }}
        retry gerber2ems --debug --postprocess

    - name: Render graphs of post processed data
      shell: bash
      run: |
        . ./venv/Scripts/activate
        . ./vendor/update_path.sh
        cd ${{ env.SIM_DIR }}
        retry gerber2ems --debug --render

    - name: Upload gerber2ems output files
      uses: actions/upload-artifact@v4
      with:
        name: verify_win_install
        path: ${{ github.workspace }}/${{ env.SIM_DIR }}
